import 'package:flutter/material.dart';
import 'package:bibliotech/components/mapButton.dart';


enum LibraryMapType {
  ALL,
  HIGHLIGHT
}
class LibraryMap extends StatelessWidget {
  final double deweyDecimal;
  final LibraryMapType libraryMapType;

  LibraryMap(this.libraryMapType, {this.deweyDecimal});

  @override
  Widget build(BuildContext context) {
    return new Padding(
      padding: const EdgeInsets.only(left: 20.0, right: 20.0),
      // Used a [CustomScrollView] because it allowed us to combine both List and Grid elements
      child: new CustomScrollView(
        slivers: <Widget>[
          new SliverGrid.count(
            crossAxisCount: 3,
            children: <Widget>[
              // N.B. These comments apply to the rest of the regions
              // [MapButton] can be found in components/mapButton.dart 
              new MapButton(
                startsWith: 0,
                // Assigns the button a specific tile region
                image: new AssetImage('assets/map/000.png'),
                // Draws the label for this region on top of it
                title: "000-099\nGeneral",
                // The message to be used in the pop up generated by tapping
                message: "Here you can find general information texts, such as encyclopedias or reference texts.",
                // Determines if the tile is active or not by enumerating
                  // 1) the list type (should all books be shown or only highlighted ones?)
                  // 2) does this region contain the desired book (only reached if in HIGHLIGHT type)
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          // Takes the dewey decimal number of the book and floor divides to the nearest 100
                          // e.g. 812.54~/100 => 8
                          : deweyDecimal~/100 == 0),
                // Each tile has a different background color when active
                color: Colors.purpleAccent[100],  
              ),
              new MapButton(
                startsWith: 1,
                image: new AssetImage('assets/map/100.png'),
                title: "100-199\nPhilosophy and Psychology",
                message: "Here you can find books written by the world's great philosophers! From Aristotle to Dostoevsky!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 1), //deweyDecimal~/100 == 1,
                color: Colors.deepPurpleAccent[100],   
              ),
              new MapButton(
                startsWith: 2,
                image: new AssetImage('assets/map/200.png'),
                title: "200-299\nReligion and Mythology",
                message: "Read up on the world's numerous religions and theological texts!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 2),
                color: Colors.indigoAccent[100]  
              ),
              new MapButton(
                startsWith: 3,
                image: new AssetImage('assets/map/300.png'),
                title: "300-399\nSocial Sciences",
                message: "Find out how society runs, read up on Law and the major governments of the world in the Social Science section.",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 3),
                color: Colors.blueAccent[100]  
              ),
              new MapButton(
                startsWith: 4,
                image: new AssetImage('assets/map/400.png'),
                title: "400-499\nLanguage",
                message: "Want to pick up a new language or read foreign texts? Find them here.",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 4),
                color: Colors.tealAccent[100]
              ),
              new MapButton(
                startsWith: 5,
                image: new AssetImage('assets/map/500.png'),
                title: "500-599\nNatural Science",
                message: "Discover the world around you!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 5),
                color: Colors.greenAccent[100]
              ),
              new MapButton(
                startsWith: 6,
                image: new AssetImage('assets/map/600.png'),
                title: "600-699\nTechnology",
                message: "Want to be a doctor, an engineer, or any applied science? Find books on that here!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 6),
                color: Colors.lightGreenAccent[100]
              ),
              new MapButton(
                startsWith: 7,
                image: new AssetImage('assets/map/700.png'),
                title: "700-799\nArts",
                message: "Here you can find works from DaVinci to Picasso and more!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 7),
                color: Colors.limeAccent[100]
              ),
              new MapButton(
                startsWith: 8,
                image: new AssetImage('assets/map/800.png'),
                title: "800-899\nLiterature",
                message: "Find all of the classics here! From Catcher in the Rye to Hamlet, you can find it here!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 8),
                color: Colors.amberAccent[100]
              ),
              new Container(),
              new MapButton(
                startsWith: 9,
                image: new AssetImage('assets/map/900.png'),
                title: "900-999\nGeography and History",
                message: "Find and atlas or a history textbook in this section!",
                active: (libraryMapType == LibraryMapType.ALL
                          ? true
                          : deweyDecimal~/100 == 9),
                color: Colors.deepOrangeAccent[100]
              ),
              new Container()
            ]
          ),
          // Converts a standard widget to a sliver
          new SliverToBoxAdapter(
            // Gives the user information about how to interact with the map
            child: new Container(
              padding: const EdgeInsets.all(8.0),
              child: new Text("Tap on a region to find more information", textAlign: TextAlign.center,),
            )
          )
        ]
      )
    );
  }
}